version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: inlog-postgres
    restart: always
    environment:
      POSTGRES_DB: InlogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: inlog-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: Inlog.Desafio.Backend.WebApi/Dockerfile
    container_name: inlog-backend
    depends_on:
      - postgres
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__inlogDB=Host=postgres;Port=5432;Database=InlogDb;Username=postgres;Password=postgres

  frontend:
    build:
      context: ../../front-end/inlog-frontend
      dockerfile: Dockerfile
    container_name: inlog-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../../front-end/inlog-frontend:/app
    working_dir: /app
    command: npm run start -- --host 0.0.0.0 --port 4200
    depends_on:
      - backend

volumes:
  pgdata:
